---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - hunting.zoli.com
  resources:
  - bowhunters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hunting.zoli.com
  resources:
  - bowhunters/finalizers
  verbs:
  - update
- apiGroups:
  - hunting.zoli.com
  resources:
  - bowhunters/status
  verbs:
  - get
  - patch
  - update
